version: '3'

services:
  frontend:
      build:
        context: tfeeter-frontend
      image: tfeeter-frontend:latest
      environment:
        - APP_BACKEND=http://192.168.8.20
        - KEYCLOAK_REALM=tfeeter
        - KEYCLOAK_CLIENT=tfeeter-ui
        - KEYCLOAK_DOMAIN_ADDRESS=http://192.168.8.20:8080/auth
      ports:
      - 4200:80
  backend:
      build:
        context: tfeeter-backend
      image: tfeeter-backend:latest
      environment:
        - KEYCLOAK_DOMAIN_ADDRESS=http://192.168.8.20:8080/auth
        - KEYCLOAK_REALM_NAME=tfeeter
        - KEYCLOAK_CLIENT_NAME=tfeeter-backend
        - KEYCLOAK_CLIENT_SECRET=c44a9d4a-7e80-4672-a931-cf6848670a5f
      ports:
        - 8090:8090
      volumes:
        - tfeeter_data:/opt/app/db
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:11.0.2
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      command:
        - -Dkeycloak.migration.action=import
        - -Dkeycloak.migration.provider=singleFile
        - -Dkeycloak.migration.strategy=IGNORE_EXISTING
        - -Dkeycloak.migration.file=/opt/jboss/keycloak-config.json
      ports:
        - 8080:8080
      depends_on:
        - postgres
      volumes:
      - ./keycloak-config.json:/opt/jboss/keycloak-config.json
volumes:
  tfeeter_data:
    driver: local
  postgres_data:
    driver: local
